export const LAUNCHPAD_ABI = [
  {
    inputs: [],
    name: "presaleCounter",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "tokenAddress", type: "address" },
      { internalType: "uint256", name: "tokenPrice", type: "uint256" },
      { internalType: "uint256", name: "softcap", type: "uint256" },
      { internalType: "uint256", name: "hardcap", type: "uint256" },
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "endTime", type: "uint256" },
      { internalType: "uint256", name: "maxBuyPerUser", type: "uint256" },
    ],
    name: "createPresale",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "buyTokens",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "claimTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "withdrawFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "getPresaleDetails",
    outputs: [
      {
        components: [
          { internalType: "address", name: "tokenAddress", type: "address" },
          { internalType: "address", name: "owner", type: "address" },
          { internalType: "uint256", name: "tokenPrice", type: "uint256" },
          { internalType: "uint256", name: "softcap", type: "uint256" },
          { internalType: "uint256", name: "hardcap", type: "uint256" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "endTime", type: "uint256" },
          { internalType: "uint256", name: "maxBuyPerUser", type: "uint256" },
          { internalType: "uint256", name: "totalRaised", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
          { internalType: "bool", name: "isFinalized", type: "bool" },
        ],
        internalType: "struct Launchpad.PresaleConfig",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "presaleId", type: "uint256" },
      { internalType: "address", name: "user", type: "address" },
    ],
    name: "getUserContribution",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "amount", type: "uint256" },
          { internalType: "uint256", name: "tokenAmount", type: "uint256" },
          { internalType: "bool", name: "claimed", type: "bool" },
        ],
        internalType: "struct Launchpad.UserContribution",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "refundContribution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // ── Funding flow ────────────────────────────────────────────
  {
    inputs: [
      { internalType: "uint256", name: "presaleId", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "fundPresale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "getRequiredTokens",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "presaleId", type: "uint256" }],
    name: "getFundingStatus",
    outputs: [
      { internalType: "uint256", name: "required", type: "uint256" },
      { internalType: "uint256", name: "funded", type: "uint256" },
      { internalType: "uint256", name: "committed", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "presaleTokensFunded",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "presaleId", type: "uint256" },
      { indexed: true, internalType: "address", name: "funder", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "PresaleFunded",
    type: "event",
  },
];
